state_dim: 16
kl_weight: 10.0
chunk_size: 50
hidden_dim: 512
dim_feedforward: 3200
temporal_agg: true
device: cuda:0
ckpt_dir: null
policy_class: ACT
num_steps: 20000
batch_size: 64
save_freq: 5000
position_embedding: sine
lr_vision_backbone: 1.0e-05
weight_decay: 0.0001
lr: 1.0e-05
masks: false
dilation: false
backbone: resnet18
nheads: 8
enc_layers: 4
dec_layers: 7
pre_norm: false
dropout: 0.1
camera_names:
- cam_high
- cam_wrist
- cam_wrist_b
tactile_names:
- tac_left
- tac_right
- tac_left_b
- tac_right_b
lr_tactile_backbone: 1.0e-05
tactile_masks: false
tactile_backbone: resnet18
tactile_ckpt: null
tactile_dilation: false
num_epochs: 6000
